import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

const translations = {
  ru: {
    // Header
    home: 'Главная',
    favorites: 'Избранное',
    cart: 'Корзина',
    login: 'Войти',
    logout: 'Выйти',
    profile: 'Профиль',

    // HomePage
    heroTitle: 'Экипировка для движения вперед',
    heroDesc: 'Кроссовки, одежда и аксессуары для тренировок, города и новых целей.',
    searchPlaceholder: 'Найти товар',
    addToCart: 'В корзину',
    all: 'Все',
    sneakers: 'Кроссовки',
    clothing: 'Одежда',
    accessories: 'Аксессуары',
    noProducts: 'Товары не найдены.',
    addToFavorites: 'Добавить в избранное',
    removeFromFavorites: 'Убрать из избранного',

    // Cart
    cartTitle: 'Корзина',
    cartEmpty: 'Корзина пуста',
    cartEmptyDesc: 'Добавьте товары, чтобы они появились здесь',
    goToCatalog: 'Перейти в каталог',
    clearCart: 'Очистить корзину',
    delivery: 'Доставка',
    free: 'Бесплатно',
    total: 'Итого',
    checkout: 'Перейти к оформлению',
    remove: 'Удалить',
    size: 'Размер',
    items: 'Товаров',

    // Favorites
    favoritesTitle: 'Избранное',
    noFavorites: 'Нет избранных товаров',
    noFavoritesDesc: 'Добавляйте товары в избранное, чтобы не потерять их',

    // Profile
    loginRequired: 'Войдите в аккаунт',
    loginRequiredDesc: 'Чтобы видеть профиль и историю заказов',
    personalInfo: 'Личные данные',
    orderHistory: 'История заказов',
    settings: 'Настройки',
    edit: 'Редактировать',
    save: 'Сохранить',
    name: 'Имя',
    phone: 'Телефон',
    address: 'Адрес',
    notSpecified: 'Не указан',
    phonePlaceholder: '+7 (___) ___-__-__',
    addressPlaceholder: 'Город, улица, дом',
    delivered: 'Доставлен',
    inTransit: 'В пути',
    noOrders: 'У вас пока нет заказов',
    orderTotal: 'Итого',
    notifications: 'Уведомления о заказах',
    notificationsDesc: 'Получать email о статусе заказов',
    mailing: 'Рассылки',
    mailingDesc: 'Получать акции и новинки',
    language: 'Язык',
    deleteAccount: 'Удалить аккаунт',
    deleteAccountDesc: 'Это действие необратимо. Все данные будут удалены.',
    deleteAccountBtn: 'Удалить аккаунт',
    deleteAccountConfirm: 'Вы уверены, что хотите удалить аккаунт? Это действие необратимо!',
    cancel: 'Отмена',
    confirm: 'Да, удалить',

    // Login
    loginSubtitle: 'Войдите в свой аккаунт',
    or: 'или',
    signInTab: 'Вход',
    registerTab: 'Регистрация',
    email: 'Email',
    password: 'Пароль',
    rememberMe: 'Запомнить меня',
    forgotPassword: 'Забыли пароль?',
    signIn: 'Войти',

    fullName: 'Имя',
    namePlaceholder: 'Ваше имя',
    confirmPassword: 'Повторите пароль',
    minChars: 'Минимум 6 символов',
    agreeTerms: 'Я согласен с',
    terms: 'условиями',
    privacy: 'политикой конфиденциальности',
    createAccount: 'Создать аккаунт',
    fillAllFields: 'Заполните все поля',
    wrongCredentials: 'Неверный email или пароль',
    passwordsMismatch: 'Пароли не совпадают',
    passwordTooShort: 'Пароль должен быть не менее 6 символов',

    // Product Detail
    backToCatalog: 'Назад в каталог',
    selectSize: 'Выберите размер',
    noSize: 'Без размера',
    catalog: 'Каталог',
    productNotFound: 'Товар не найден',
    productNotFoundDesc: 'Такого товара не существует',
    goToHome: 'На главную',
    quantity: 'Количество',
    added: '✓ Добавлено',
    freeShipping: 'Бесплатная доставка',
    return14: 'Возврат 14 дней',
    qualityGuarantee: 'Гарантия качества',
    safePayment: 'Безопасная оплата',
    description: 'Описание',
    reviews: 'Отзывы',
    relatedProducts: 'Похожие товары',
    category: 'Категория',
    brand: 'Бренд',
    season: 'Сезон',
    country: 'Страна производства',
    article: 'Артикул',
    courier: 'Курьером',
    courierDesc: 'Бесплатно, 1-3 рабочих дня',
    pickup: 'Самовывоз',
    pickupDesc: 'Из магазина Sport House',
    express: 'Экспресс',
    expressDesc: 'В течение дня',
    reviewsCount: 'отзывов',

    // Checkout
    checkoutTitle: 'Оформление заказа',
    firstName: 'Имя',
    lastName: 'Фамилия',
    city: 'Город',
    zipCode: 'Индекс',
    cardNumber: 'Номер карты',
    expiry: 'Срок действия',
    cvv: 'CVV',
    placeOrder: 'Оформить заказ',
    contactInfo: 'Контактные данные',
    deliveryMethod: 'Способ доставки',
    deliveryAddress: 'Адрес доставки',
    streetPlaceholder: 'ул., дом, квартира',
    next: 'Далее',
    back: 'Назад',
    paymentMethod: 'Способ оплаты',
    bankCard: 'Банковская карта',
    cashOnDelivery: 'Наличными при получении',
    sbp: 'СБП',
    yourOrder: 'Ваш заказ',
    confirmOrder: 'Подтвердить заказ',
    orderPlaced: 'Заказ оформлен!',
    orderNumber: 'Номер заказа:',
    confirmationSent: 'Мы отправим подтверждение на',
    continueShopping: 'Продолжить покупки',
    addProductsFirst: 'Добавьте товары перед оформлением заказа',
    payment: 'Оплата',
    recipient: 'Получатель',
    offerTerms: 'условиями оферты',
  },

  en: {
    // Header
    home: 'Home',
    favorites: 'Favorites',
    cart: 'Cart',
    login: 'Sign In',
    logout: 'Sign Out',
    profile: 'Profile',

    // HomePage
    heroTitle: 'Gear for moving forward',
    heroDesc: 'Sneakers, clothing and accessories for workouts, city and new goals.',
    searchPlaceholder: 'Search products',
    addToCart: 'Add to cart',
    all: 'All',
    sneakers: 'Sneakers',
    clothing: 'Clothing',
    accessories: 'Accessories',
    noProducts: 'No products found.',
    addToFavorites: 'Add to favorites',
    removeFromFavorites: 'Remove from favorites',

    // Cart
    cartTitle: 'Cart',
    cartEmpty: 'Cart is empty',
    cartEmptyDesc: 'Add products to see them here',
    goToCatalog: 'Go to catalog',
    clearCart: 'Clear cart',
    delivery: 'Delivery',
    free: 'Free',
    total: 'Total',
    checkout: 'Proceed to checkout',
    remove: 'Remove',
    size: 'Size',
    items: 'Items',

    // Favorites
    favoritesTitle: 'Favorites',
    noFavorites: 'No favorite products',
    noFavoritesDesc: 'Add products to favorites so you don\'t lose them',

    // Profile
    loginRequired: 'Sign in to your account',
    loginRequiredDesc: 'To see your profile and order history',
    personalInfo: 'Personal Info',
    orderHistory: 'Order History',
    settings: 'Settings',
    edit: 'Edit',
    save: 'Save',
    name: 'Name',
    phone: 'Phone',
    address: 'Address',
    notSpecified: 'Not specified',
    phonePlaceholder: '+1 (___) ___-__-__',
    addressPlaceholder: 'City, street, house',
    delivered: 'Delivered',
    inTransit: 'In transit',
    noOrders: 'You have no orders yet',
    orderTotal: 'Total',
    notifications: 'Order notifications',
    notificationsDesc: 'Receive email about order status',
    mailing: 'Mailing list',
    mailingDesc: 'Receive promotions and new arrivals',
    language: 'Language',
    deleteAccount: 'Delete Account',
    deleteAccountDesc: 'This action is irreversible. All data will be deleted.',
    deleteAccountBtn: 'Delete Account',
    deleteAccountConfirm: 'Are you sure you want to delete your account? This action is irreversible!',
    cancel: 'Cancel',
    confirm: 'Yes, delete',

    // Login
    loginSubtitle: 'Sign in to your account',
    or: 'or',
    signInTab: 'Sign In',
    registerTab: 'Register',
    email: 'Email',
    password: 'Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    signIn: 'Sign In',

    fullName: 'Name',
    namePlaceholder: 'Your name',
    confirmPassword: 'Confirm password',
    minChars: 'Minimum 6 characters',
    agreeTerms: 'I agree to the',
    terms: 'terms',
    privacy: 'privacy policy',
    createAccount: 'Create Account',
    fillAllFields: 'Fill in all fields',
    wrongCredentials: 'Invalid email or password',
    passwordsMismatch: 'Passwords don\'t match',
    passwordTooShort: 'Password must be at least 6 characters',

    // Product Detail
    backToCatalog: 'Back to catalog',
    selectSize: 'Select size',
    noSize: 'No size',
    catalog: 'Catalog',
    productNotFound: 'Product not found',
    productNotFoundDesc: 'This product does not exist',
    goToHome: 'Go to home',
    quantity: 'Quantity',
    added: '✓ Added',
    freeShipping: 'Free shipping',
    return14: '14-day returns',
    qualityGuarantee: 'Quality guarantee',
    safePayment: 'Safe payment',
    description: 'Description',
    reviews: 'Reviews',
    relatedProducts: 'Related products',
    category: 'Category',
    brand: 'Brand',
    season: 'Season',
    country: 'Country of origin',
    article: 'Article',
    courier: 'Courier',
    courierDesc: 'Free, 1-3 business days',
    pickup: 'Pickup',
    pickupDesc: 'From Sport House store',
    express: 'Express',
    expressDesc: 'Within the day',
    reviewsCount: 'reviews',

    // Checkout
    checkoutTitle: 'Checkout',
    firstName: 'First name',
    lastName: 'Last name',
    city: 'City',
    zipCode: 'Zip code',
    cardNumber: 'Card number',
    expiry: 'Expiry',
    cvv: 'CVV',
    placeOrder: 'Place order',
    contactInfo: 'Contact Information',
    deliveryMethod: 'Delivery Method',
    deliveryAddress: 'Delivery Address',
    streetPlaceholder: 'street, house, apartment',
    next: 'Next',
    back: 'Back',
    paymentMethod: 'Payment Method',
    bankCard: 'Bank Card',
    cashOnDelivery: 'Cash on delivery',
    sbp: 'SBP',
    yourOrder: 'Your Order',
    confirmOrder: 'Confirm Order',
    orderPlaced: 'Order Placed!',
    orderNumber: 'Order number:',
    confirmationSent: 'We will send confirmation to',
    continueShopping: 'Continue Shopping',
    addProductsFirst: 'Add products before checkout',
    payment: 'Payment',
    recipient: 'Recipient',
    offerTerms: 'offer terms',
  },

  uz: {
    // Header
    home: 'Bosh sahifa',
    favorites: 'Tanlanganlar',
    cart: 'Savat',
    login: 'Kirish',
    logout: 'Chiqish',
    profile: 'Profil',

    // HomePage
    heroTitle: 'Oldinga harakatlanish uchun jihozlar',
    heroDesc: 'Mashg\'ulotlar, shahar va yangi maqsadlar uchun krossovka, kiyim va aksessuarlar.',
    searchPlaceholder: 'Mahsulot qidirish',
    addToCart: 'Savatga qo\'shish',
    all: 'Hammasi',
    sneakers: 'Krossovka',
    clothing: 'Kiyim',
    accessories: 'Aksessuarlar',
    noProducts: 'Mahsulotlar topilmadi.',
    addToFavorites: 'Tanlanganlarga qo\'shish',
    removeFromFavorites: 'Tanlanganlardan o\'chirish',

    // Cart
    cartTitle: 'Savat',
    cartEmpty: 'Savat bo\'sh',
    cartEmptyDesc: 'Mahsulotlarni qo\'shing, ular yerda paydo bo\'ladi',
    goToCatalog: 'Katalogga o\'tish',
    clearCart: 'Savatni tozalash',
    delivery: 'Yetkazish',
    free: 'Bepul',
    total: 'Jami',
    checkout: 'Buyurtma berish',
    remove: 'O\'chirish',
    size: 'O\'lcham',
    items: 'Mahsulotlar',

    // Favorites
    favoritesTitle: 'Tanlanganlar',
    noFavorites: 'Tanlangan mahsulotlar yo\'q',
    noFavoritesDesc: 'Mahsulotlarni yo\'qotmaslik uchun tanlanganlarga qo\'shing',

    // Profile
    loginRequired: 'Hisobingizga kiring',
    loginRequiredDesc: 'Profilni va buyurtmalar tarixini ko\'rish uchun',
    personalInfo: 'Shaxsiy ma\'lumotlar',
    orderHistory: 'Buyurtmalar tarixi',
    settings: 'Sozlamalar',
    edit: 'Tahrirlash',
    save: 'Saqlash',
    name: 'Ism',
    phone: 'Telefon',
    address: 'Manzil',
    notSpecified: 'Ko\'rsatilmagan',
    phonePlaceholder: '+998 (__) ___-__-__',
    addressPlaceholder: 'Shahar, ko\'cha, uy',
    delivered: 'Yetkazildi',
    inTransit: 'Yo\'lda',
    noOrders: 'Hali buyurtmalaringiz yo\'q',
    orderTotal: 'Jami',
    notifications: 'Buyurtma xabarlari',
    notificationsDesc: 'Buyurtma holati haqida email olish',
    mailing: 'Xabarlar',
    mailingDesc: 'Aksiyalar va yangiliklar olish',
    language: 'Til',
    deleteAccount: 'Hisobni o\'chirish',
    deleteAccountDesc: 'Bu qaytarib bo\'lmaydigan harakat. Barcha ma\'lumotlar o\'chiriladi.',
    deleteAccountBtn: 'Hisobni o\'chirish',
    deleteAccountConfirm: 'Hisobingizni o\'chirishni xohlaysizmi? Bu qaytarib bo\'lmaydi!',
    cancel: 'Bekor qilish',
    confirm: 'Ha, o\'chirish',

    // Login
    loginSubtitle: 'Hisobingizga kiring',
    or: 'yoki',
    signInTab: 'Kirish',
    registerTab: 'Ro\'yxatdan o\'tish',
    email: 'Email',
    password: 'Parol',
    rememberMe: 'Meni eslab qolish',
    forgotPassword: 'Parolni unutdingizmi?',
    signIn: 'Kirish',

    fullName: 'Ism',
    namePlaceholder: 'Ismingiz',
    confirmPassword: 'Parolni tasdiqlash',
    minChars: 'Kamida 6 ta belgi',
    agreeTerms: 'Men roziman',
    terms: 'shartlar',
    privacy: 'maxfiylik siyosati',
    createAccount: 'Hisob yaratish',
    fillAllFields: 'Barcha maydonlarni to\'ldiring',
    wrongCredentials: 'Noto\'g\'ri email yoki parol',
    passwordsMismatch: 'Parollar mos kelmaydi',
    passwordTooShort: 'Parol kamida 6 ta belgi bo\'lishi kerak',

    // Product Detail
    backToCatalog: 'Katalogga qaytish',
    selectSize: 'O\'lchamni tanlang',
    noSize: 'O\'lchamsiz',
    catalog: 'Katalog',
    productNotFound: 'Mahsulot topilmadi',
    productNotFoundDesc: 'Bunday mahsulot mavjud emas',
    goToHome: 'Bosh sahifaga',
    quantity: 'Soni',
    added: '✓ Qo\'shildi',
    freeShipping: 'Bepul yetkazish',
    return14: '14 kun qaytarish',
    qualityGuarantee: 'Sifat kafolati',
    safePayment: 'Xavfsiz to\'lov',
    description: 'Tavsif',
    reviews: 'Sharhlar',
    relatedProducts: 'O\'xshash mahsulotlar',
    category: 'Kategoriya',
    brand: 'Brend',
    season: 'Mavsum',
    country: 'Ishlab chiqarilgan mamlakat',
    article: 'Maqola',
    courier: 'Kuryer orqali',
    courierDesc: 'Bepul, 1-3 ish kuni',
    pickup: 'Olib ketish',
    pickupDesc: 'Sport House do\'konidan',
    express: 'Ekspres',
    expressDesc: 'Kun ichida',
    reviewsCount: 'sharhlar',

    // Checkout
    checkoutTitle: 'Buyurtma berish',
    firstName: 'Ism',
    lastName: 'Familiya',
    city: 'Shahar',
    zipCode: 'Pochta indeksi',
    cardNumber: 'Karta raqami',
    expiry: 'Muddati',
    cvv: 'CVV',
    placeOrder: 'Buyurtma berish',
    contactInfo: 'Aloqa ma\'lumotlari',
    deliveryMethod: 'Yetkazish usuli',
    deliveryAddress: 'Yetkazish manzili',
    streetPlaceholder: 'ko\'cha, uy, xona',
    next: 'Keyingi',
    back: 'Orqaga',
    paymentMethod: 'To\'lov usuli',
    bankCard: 'Bank kartasi',
    cashOnDelivery: 'Yetkazganda naqd pul',
    sbp: 'SBP',
    yourOrder: 'Buyurtmangiz',
    confirmOrder: 'Buyurtmani tasdiqlash',
    orderPlaced: 'Buyurtma berildi!',
    orderNumber: 'Buyurtma raqami:',
    confirmationSent: 'Tasdiqlashni yuboramiz',
    continueShopping: 'Xaridni davom ettirish',
    addProductsFirst: 'Buyurtma berishdan oldin mahsulotlar qo\'shing',
    payment: 'To\'lov',
    recipient: 'Qabul qiluvchi',
    offerTerms: 'offer shartlari',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('sporthouse_lang') || 'ru';
  });

  useEffect(() => {
    localStorage.setItem('sporthouse_lang', language);
  }, [language]);

  const t = (key) => translations[language]?.[key] || translations.ru[key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
